version: '3.7'
services:
  frontend:
    build:
      context: './frontend'
    ports:
      - 8501:8501
    depends_on:
      - api
    volumes:
      - ./frontend/src:/usr/src/app/src
  api:
    build:
      context: './api'
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=postgres://jigsawlabs:secret@db:5432/jigsawlabs
    depends_on:
      - db
    volumes:
      - ./api/restaurants:/usr/src/app/restaurants
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: jigsawlabs
      POSTGRES_PASSWORD: secret
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
      - ./db:/docker-entrypoint-initdb.d/
volumes:
  postgres_data:
